PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE members (id integer primary key, name text, email text, password text);
INSERT INTO "members" VALUES(1,'Abby Wiggins','aw@email.com','123456');
INSERT INTO "members" VALUES(2,'Emily Red','er@email.com','123456');
INSERT INTO "members" VALUES(3,'Luna Lovegood','ll@email.com','123123');
INSERT INTO "members" VALUES(4,'Riella Winchester','rw@email.com','121212');
INSERT INTO "members" VALUES(5,'Charlotte Dodd','cd@email.com','444444');
INSERT INTO "members" VALUES(6,'Sam Smith','ss@email.com','444555');
INSERT INTO "members" VALUES(7,'Alan Herring','ah@email.com','431565');
INSERT INTO "members" VALUES(8,'Yoda Johnson','yj@email.com','6tyhgt');
INSERT INTO "members" VALUES(9,'Ursula Reed','ur@email.com','6t4gg3');
INSERT INTO "members" VALUES(10,'Adam Lovelace','al@email.com','abcdef');
CREATE TABLE profile (age integer, positions text, responsibilities text, id integer, foreign key(id) references members(id));
INSERT INTO "profile" VALUES(21,'1','none',1);
INSERT INTO "profile" VALUES(22,'5','none',2);
INSERT INTO "profile" VALUES(20,'5, 4','none',3);
INSERT INTO "profile" VALUES(18,'3','treasurer',4);
INSERT INTO "profile" VALUES(19,'11','social sec',5);
INSERT INTO "profile" VALUES(23,'12, 13','none',6);
INSERT INTO "profile" VALUES(21,'1, 3','none',7);
INSERT INTO "profile" VALUES(26,'11, 14','none',8);
INSERT INTO "profile" VALUES(23,'2','captain',9);
INSERT INTO "profile" VALUES(21,'9','vice captain',10);
COMMIT;
